package com.frontlinehomes.save2buy.data.account.response;

import com.frontlinehomes.save2buy.data.account.data.*;
import com.frontlinehomes.save2buy.data.land.data.InvestorLand;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.ManyToOne;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.CurrentTimestamp;
import java.sql.Timestamp;

@Setter
@Getter
@NoArgsConstructor
@AllArgsConstructor
public class TransactionResponseDTO {

    private Long id;

    private Timestamp createdTime;

    private Double amount;

    private String landTitle;

    /** Transaction reference is generated by save2buy.ng **/
    private String refNumber;

    /**
     *
     * Channel describes  the integrated payment provider
     */
    private Channel channel;

    /**
     *
     * transactionId is generated by the payment service provider
     */
    private String transactionId;

    private String paymentMethod;

    @Enumerated(EnumType.STRING)
    private BillingType billingType;
    @Enumerated(EnumType.STRING)
    private TransactionStatus transactionStatus;

    @Enumerated(EnumType.STRING)
    private TransactionType type;

}
