package com.frontlinehomes.save2buy.data.account.response;

import com.frontlinehomes.save2buy.data.account.data.*;
import com.frontlinehomes.save2buy.data.land.data.InvestorLand;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.ManyToOne;
import org.hibernate.annotations.CurrentTimestamp;
import java.sql.Timestamp;


public class TransactionResponseDTO {

    private Long id;

    private InvestorLand investorLand;

    private Account account;


    private Timestamp createdTime;

    private Double amount;

    /** Transaction reference is generated by save2buy.ng **/
    private String refNumber;

    /**
     *
     * Channel describes  the integrated payment provider
     */
    private Channel channel;

    /**
     *
     * transactionId is generated by the payment service provider
     */
    private String transactionId;

    private String paymentMethod;

    @Enumerated(EnumType.STRING)
    private BillingType billingType;
    @Enumerated(EnumType.STRING)
    private TransactionStatus transactionStatus;

    @Enumerated(EnumType.STRING)
    private TransactionType type;

}
